
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/email?useSSL=false&useUnicode=true&serverTimezome=Asia/Seoul
    username: root
    password: kang!754105
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  jwt:
    secretKey: cos
  mvc:
    view:
      prefix: /WEB-INF/view
      suffix: .jsp
